version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5057:5057'
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/risevest_db?schema=public
      REDIS_URL: redis://redis:6379
      PORT: 5057

  postgres:
    image: postgres:latest
    restart: always
    container_name: risevest-db
    ports:
      - '6500:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: risevest_db
    volumes:
      - pg_data:/var/lib/postgresql/data
      -  ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
